id: IF5143409
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T18:00:17.709959'
last_modified: '2022-06-19T18:00:17.709964'
parser: null
source_metadata:
  title: Vajraṇakhī Series
  language: de
  description: 'A series of texts related to the wrathful ḍākinī Vajraṇakhī (rdo
    rje sder mo) or ‘Vajra Claws’:'
  volume:
    fD2B9:
      title: Introduction to Vajraṇakhī
      base_file: fD2B9.txt
      order: 1
      parent: Introduction
    f61B4:
      title: The Dhāraṇī of Glorious Vajraṇakhī
      base_file: f61B4.txt
      order: 2
      parent: Dhāraṇī
    fD597:
      title: Brief Dhāraṇī of Glorious Vajraṇakhī
      base_file: fD597.txt
      order: 3
      parent: Dhāraṇī
    fDCC1:
      title: A Daily Practice of Vajraṇakhī
      base_file: fDCC1.txt
      order: 4
      parent: Sādhanas
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
